Ensure this does not run for branches or other random pushes - filtering on tags is not enough

diff --git a/.github/workflows/merge-to-stable.yml b/.github/workflows/merge-to-stable.yml
--- a/.github/workflows/merge-to-stable.yml
+++ b/.github/workflows/merge-to-stable.yml
@@ -40,7 +40,7 @@ on:
 
 jobs:
   build:
-
+    if: github.ref_type = tag
     runs-on: ubuntu-latest
 
     steps:
@@ -101,4 +101,4 @@ jobs:
         run: cd $GITHUB_WORKSPACE/cactus && git push
 
       - name: Delete Tag
-        run: cd $GITHUB_WORKSPACE/cactus && git push --delete origin $GITHUB_REF_NAME
+        run: cd $GITHUB_WORKSPACE/cactus && git push --delete origin $GITHUB_REF_NAME || echo "Could not delete $GITHUB_REF_NAME"
